### ISSUE TITLE
Review readme

### ISSUE THREAD

**Issue by nmeylan** [nmeylan/rust-ro#18]
Clarify the status of the project.

- [x] Create Meta issue
- [x] Review tasks
- [x] Review what has been done
- [x] Write contributing.MD
- [x] Review architecture page
- [x] Write about supported packets

**Comment by DanielHe4rt** [comment]
Wanna some help to maintain the project? Loved your initiative and I want to learn more about Rust as well!

**Comment by DanielHe4rt** [comment]
Did some minor improvements on #26
