### ISSUE TITLE
Docs: Tooling Build

### ISSUE THREAD

**Issue by DanielHe4rt** [nmeylan/rust-ro#34]
Hey, how you doing? 

So, I saw that the project counts with `cargo-watch` and maybe it will be helpful to let some commands that you may use on the documentation. 

There's anything specific that you usually use there or..?

**Comment by nmeylan** [comment]
Hello, i was not aware of what is `cargo-watch` i can update readme with command i run but they are basics one

**Comment by DanielHe4rt** [comment]
Sounds good! Closing the issue.
