### ISSUE TITLE
Docs: command for setup DB with docker

### ISSUE THREAD

**Issue by Rafael-Ramosc** [nmeylan/rust-ro#40]
Command for setup the DB with docker for me didnt work, so i used "docker-compose up --build" instead of "docker-compose up -d".

**Comment by nmeylan** [comment]
I am not sure to understand  why, the docker compose only start and init a database, the image is `postgres:15-alpine` which is already built, so adding `--build` to docker-compose has no effect.

What do you mean by it didn't work? can you share the error?

**Comment by nmeylan** [comment]
closing as no update, happy to reopen if needed
