### ISSUE TITLE
Need help to setup project

### ISSUE THREAD

**Issue by Rafael-Ramosc** [nmeylan/rust-ro#48]
I followed the instructions to start the project, but I got stuck at the Ragnarok client. I can't run it without Python 2. I tried to install Python 2, but I encountered some issues with the default Linux setup.

I'm new to Rust and mainly a web programmer, so I'm not very familiar with this kind of project. I would really appreciate some guidance to get started. I have a genuine interest in contributing to this project.

**Comment by nmeylan** [comment]
Hello thanks for your interest for this project.
Unfortunately I can't provide support for client setup as it is not related at all to this project.
I personally use robrowser which only needs an http server, and does not require to install python so i can't help on this
